name 'chef-essentials-hackday-2016'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-essentials-hackday-2016'
long_description 'Installs/Configures chef-essentials-hackday-2016'
version '0.3.0'

depends 'windows'
depends 'iis'
depends 'windows_firewall'